# Generated by Django 3.1.7 on 2021-03-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('user', '0001_initial'),
        ('book', '0002_auto_20210330_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_people',
            field=models.ManyToManyField(related_name='booked_rooms', through='book.Book', to='user.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.checkintype'),
        ),
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.city'),
        ),
        migrations.AddField(
            model_name='room',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.district'),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.host'),
        ),
        migrations.AddField(
            model_name='room',
            name='reviews',
            field=models.ManyToManyField(related_name='reviewed_room', through='room.Review', to='user.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_conveniences',
            field=models.ManyToManyField(related_name='convenience_rooms', through='room.RoomConvenience', to='room.Convenience'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_rules',
            field=models.ManyToManyField(related_name='rule_rooms', through='room.RoomRule', to='room.Rule'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.type'),
        ),
        migrations.AddField(
            model_name='room',
            name='wished_people',
            field=models.ManyToManyField(related_name='wished_rooms', through='user.Wish', to='user.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='image',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.city'),
        ),
        migrations.AddField(
            model_name='addressline',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.city'),
        ),
        migrations.AddField(
            model_name='addressline',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.district'),
        ),
    ]
